# -*- coding: utf-8 -*-
"""20L-2074_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncJau2f0XMxMG4ploziMwwdyCQqI88H3
"""

def sqr(x):
  return x**0.5

num1=input("Enter the number : ")
num=int(num1)
out=sqr(num)
print("Square root of no is :",out)