# -*- coding: utf-8 -*-
"""20L-2074_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vkOvM9UUcwNUdutrRoU3fV0uyKPUaQHU
"""

def rev(arr):
 start=0
 end=size-1
 while start<end :
  temp=arr[start]
  arr[start]=arr[end]
  arr[end]=temp
  start=start+1
  end=end-1

array=["h","e","l","l","o"]
size=len(array)
print('string befor reversing : ',array)
rev(array)
print('string befor reversing :',array)